### ISSUE TITLE
Displaying the QR code on the Passport v2

### ISSUE THREAD

**Issue by Byte1122** [Foundation-Devices/passport2#32]
I have trouble scanning the QR code from different wallets. The camera on different phones have trouble auto focussing on the screen. Also the same for computer camera. Increasing the animated QR code size or lower the brightness are not helpful. 

It might be related to general problem of autofocus on white screen (this is a common problem).
See here also: https://photo.stackexchange.com/questions/9095/why-doesnt-auto-focus-work-with-an-all-white-subject-like-a-wall

A solution is to make the white background another color, like grey, so all camera can detect the QR code and the edge of the screen.

**Comment by Byte1122** [comment]
**Update:** I have narrowed down the issue. The primary problem lies in scanning the code from the mobile device. It appears that the iPhone 14 Pro has a unique feature that allows it to use different lenses. As a result, the app (bluewallet, Envoy etc) should be updated to utilize the special lens designed for close-up scanning (Macro-mode). If not, the app will resort to using the default camera (wide lens), which does not provide a clear image for QR code scanning. In summary, third-party apps will not have access to the macro mode on the iPhone unless the developers  enable this feature within their apps.

See here also:
https://forums.macrumors.com/threads/iphone-14-pro-cant-focus-close-up-qr-codes-3rd-party-apps.2367008/

**Comment by jeandudey** [comment]
@Byte1122 thanks for reaching back!

I will be closing this one as it is an issue with iOS-related applications.
