### ISSUE TITLE
Building bootloader with `just build color` results in error

### ISSUE THREAD

**Issue by hugoender** [Foundation-Devices/passport2#335]
Tried building the bootloader as per the [DEVELOPMENT.md](https://github.com/Foundation-Devices/passport2/blob/main/DEVELOPMENT.md#building-the-bootloader) documentation and it results in the following error:

`error: Justfile does not contain recipes 'build' or 'color'.`

![Screenshot from 2023-06-14 22-33-21](https://github.com/Foundation-Devices/passport2/assets/6217175/f9f48b92-5027-4a81-8425-afdc9e0aff4c)

**Comment by jeandudey** [comment]
Sorry, the instruction is a bit outdated, to build the bootloader you need to do:

```
just build-bootloader color # or mono
```

Building the mono bootloader is not currently supported, however if you still want to build it in the https://github.com/Foundation-Devices/passport-firmware it can be done.

**Comment by hugoender** [comment]
@jeandudey I tried that and it gave another error:
```
docker run --rm -v "$PWD":/workspace -u $(id -u):$(id -g) -v $(pwd):/workspace -w /workspace -e MPY_CROSS="/workspace/mpy-cross/mpy-cross-docker" --entrypoint bash ${DOCKER_IMAGE} -c 'export PATH=$PATH:/workspace/ports/stm32/boards/Passport/tools/cosign/x86/release;just ports/stm32/boards/Passport/bootloader/build color'
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
error: Recipe `run-in-docker` failed on line 86 with exit code 126
```
![Screenshot from 2023-06-15 18-51-05](https://github.com/Foundation-Devices/passport2/assets/6217175/a7001c95-700c-4b94-8c8a-6f0ffe403aeb)

Based on the error message it seems like it's a permission issue and maybe I have to add my username to some Docker permission? If so, might want to update the documentation to handle this error.

**Comment by jeandudey** [comment]
>Based on the error message it seems like it's a permission issue and maybe I have to add my username to some Docker permission?

Yes, you have to add your user to the `docker` group in your system, it may vary per system (different distributions use different commands to add users to groups) so it isn't included in the documentation to add the user to the `docker` group, it also can have security implications for some people.

For example, any user in the docker group can be used to perform privilege escalation:

https://fosterelli.co/privilege-escalation-via-docker.html

An alternative to adding yourself to the docker group would be running the `just build-bootloader color` as `root` but that comes with other implications, e.g. `just` has to be installed system-wide and output files of the compilation will be owned by the `root` user.

That said, I will look into making it easier to compile with Docker without resorting to adding an user to the `docker` group.

**Comment by hugoender** [comment]
Thank you for the detailed response. I learned something new. I guess I'll wait for you to make it not require adding user to `docker` group before I buy a Passport so I can ensure that I can build from source without any security implications.

**Comment by jeandudey** [comment]
The https://github.com/Foundation-Devices/passport2/pull/355 pull request should allow to build the firmware without using Docker, instead Podman can be used and is rootless by default.

**Comment by jeandudey** [comment]
@hugoender closing this one as `just build-bootloader color` should work now with the 2.3.0 release (also on main branch). If it doesn't work please re-open it and I will look into it. Thanks!
