### ISSUE TITLE
Sign transaction pending menu

### ISSUE THREAD

**Issue by Byte1122** [Foundation-Devices/passport2#37]
There is pending bug in the proces of signing. When you scan an invalid QR code (for example a bitcoin address) in the Bitcoin menu (signing) the menu showing a process:

"Parsing transaction"

The QR code is invalid and the Passport will keep this process running (spinning wheel). The only way to exit is to shutdown the Passport.

Requesting:

1. quick scan if the QR code is valid or not

2. A way to cancel or go back in the menu.

**Comment by jeandudey** [comment]
Hello @Byte1122,

This should be effectively solved in the [v2.0.7](https://github.com/Foundation-Devices/passport2/releases/tag/v2.0.7) release, let me know if the problem persists to re open the issue.

Thanks for reporting!
