### ISSUE TITLE
Security Words can be enabled without successfully verifying PIN

### ISSUE THREAD

**Issue by backtopyramidone** [Foundation-Devices/passport2#447]
### The current firmware version on your Passport.

2.1.2

### Passport Model

Passport Batch 2

### Software Wallet Details

Envoy. Wallet not needed to reproduce this bug.

### Expected Behavior

When users set up two-factor authentication or change login settings on a website or other service, they typically are asked to confirm the new authentication method after setup. Allowing the confirmation to be bypassed may cause user confusion.

### Please provide the steps that you've used to reproduce the issue

1. Select Security Words under Advanced menu in Settings
2. Choose Show at Login
3. Press the BACK button at the PIN entry screen

The Show at Login option remains enabled despite no successful PIN verification

### Impact of the issue

{"label"=>"Low: Minor issue with minimal impact on usability."}

### If you found any similar or related issues, provide links to them here.

did not

**Comment by BitcoinQnA** [comment]
Thanks for the report. We have scheduled an update to the behavior in this flow for FW v2.3.0

**Comment by BitcoinQnA** [comment]
2.3.0 is now released containing a fix for this. Thank you for the report.
