### ISSUE TITLE
restore trezor wallet to passport using different derivation path.

### ISSUE THREAD

**Issue by riannom** [Foundation-Devices/passport2#455]
### Describe the new feature or improvement you would like to see in Passport's firmware.

restoring a 24 word trezor wallet to passport doesn't seem to work with sparrow or specter.  I need the derivation path of m/49'/0'/0' and nested segwit.  is there any way to get the xpub off passport to support this?  The 'connect wallet' feature always seems to export the derivation path of m/84/0/0

### Explain the specific use case or scenario where this feature would be valuable to users.

restoring a 24 word trezor wallet to passport doesn't seem to work with sparrow or specter.  I need the derivation path of m/49'/0'/0' and nested segwit.  is there any way to get this on passport?  Thanks!

**Comment by BitcoinQnA** [comment]
Hey, to achieve this with Sparrow you just need to change the policy type to the desired setting when importing. 

The export info from Passport already contains all of the relevant info.
