### ISSUE TITLE
Explore Addresses Flakyness

### ISSUE THREAD

**Issue by AndroDevcd** [Foundation-Devices/passport2#485]
### The current firmware version on your Passport.

2.3.0

### Passport Model

Passport Batch 2

### Software Wallet Details

N/A (On device)

### Expected Behavior

Explore address screen shows addresses properly when center button is pressed.

### Please provide the steps that you've used to reproduce the issue

Navigate to explore addresses screen for any wallet on the passport 2 device and attempt to view addresses 1 by 1. However, when using the center button pad and pressing the (RIGHT) button. It jumps via 10 addresses due to receiving a (DOWN) button press. The buttons are too connected together and thus make it very finicky/easy to fat-finger jumping +10 addresses preventing proper use of this functionality.

I would reccomend proposing 2 possible solutions to this issue.
-  Option 1: Using the dialpad numbers for navigating up/down 1 and up/down 10 addresses. I.e 1 & 3 for (+1/-1) and 2 & 5 for (+10/-10)
- Option 2: Provide a screen that displays a list of addresses that you can select from and allow the user to jump (+/-10) via dialpad numbers. i.e:
        [bc1dknbdjcnsdkjc..] 0 -> User selects address and is taken to the full address on screen and can show the QR code
        [bc1dknbdjcnsdkjc..] 1
        [bc1dknbdjcnsdkjc..] 2
        [bc1dknbdjcnsdkjc..] 3
        Press 1: -10 addresses
        Press 3: + 10 addresses

### Steps Taken to Resolve

Unable to use screen properly

### Impact of the issue

{"label"=>"Medium: Moderate issue affecting usability."}

### If you found any similar or related issues, provide links to them here.

N/A

**Comment by BitcoinQnA** [comment]
Thanks for the report, but this sounds like a hardware issue, not a software one. 
Could you please [contact support](https://foundation.xyz/support/) with a video detailing the issue?

Thanks!
