### ISSUE TITLE
Feature Request: Dark mode GUI

### ISSUE THREAD

**Issue by nakoshi-satamoto** [Foundation-Devices/passport2#511]
### Describe the new feature or improvement you would like to see in Passport's firmware.

A dark mode user interface with black backgrounds instead of white.

### Explain the specific use case or scenario where this feature would be valuable to users.

This would be easier on the eyes, as white backgrounds cause eye strain. This would also be more visually pleasing.

**Comment by BitcoinQnA** [comment]
@nakoshi-satamoto thanks for the suggestion. We have discussed this feature internally before now and decided not to move forward with support for it.
