### ISSUE TITLE
Feature Request: Duress pin

### ISSUE THREAD

**Issue by nakoshi-satamoto** [Foundation-Devices/passport2#512]
### Describe the new feature or improvement you would like to see in Passport's firmware.

A secondary pin code set, which could be called a duress, emergency, decoy, or wipe pin. The secondary pin when entered would wipe the keys stored in the device, the same as a reset.

### Explain the specific use case or scenario where this feature would be valuable to users.

* In an emergency where a user would need to quickly wipe the device without fully unlocking it. Or if they need to faster than the route of unlocking then going to settings then reset device.
* If an adversary is trying to extract the pin code from a user, the user could give up the duress pin code instead.
* It could be used as a decoy pin to detect attempted unauthorized access to the Passport, and even wipe the device at the same time, by having the decoy pin written down near the Passport or in an easy to find place.
* This could be a security measure by having the duress pin code easier to guess than the real pin code, so that if someone does try to guess the pin codes within the allowed number of attempts, they would likely try the duress pin code before the real one.

**Comment by BitcoinQnA** [comment]
Thanks for the suggestion @nakoshi-satamoto. We have discussed this feature at length internally before now and decided not to move forward with implementation because we strongly believe it can cause more harm than good in the wrong hands. Advanced users can already achieve decoy wallets by using passphrases.
