### ISSUE TITLE
Taproot + Multiple BIP Support?

### ISSUE THREAD

**Issue by AndroDevcd** [Foundation-Devices/passport2#581]
### Describe the new feature or improvement you would like to see in Passport's firmware.

Was wondering if there were plans to add taproot support to passport? 

Or a better question would be the ability to set the "purpose" or type of Bitcoin address structure (m/84, m/44, etc) within the device settings for single-sig + multisig wallets?

### Explain the specific use case or scenario where this feature would be valuable to users.

Not all users use the same unified "purpose" or wallet type. Some users may prefer taproot or nested segwit as their main way of interacting w/ their wallets. This could also be useful for users who have funds stuck on their wallet in a different address format that's inaccessible from many wallets due to defaulting to (m/84/0/...) derivation paths. 

This feature could provide a wider amount of flexibility using the passport device and open its usage to many more users.

### Ideas for implementation

Provide a setting in the "Bitcoin" section of device settings to "Select wallet/address type". Then provide the user w/ a list of various address types that are supported to choose from:

m/44 (P2PKH)
m/84 (P2WPKH) 
etc...

**Comment by Jacksper13** [comment]
Hey @AndroDevcd thanks for the issue! However this is already currently possible with Passport. If you pair your passport to Sparrow or Nunchuk you can create any script type wallet in them and have Passport sign transactions with them. While true Envoy currently only supports Segwit and Taproot, that is not a limitation for Passport. In fact, you can explore addresses for any script type in Passport right now. 

Does this address your concern? Let me know if you need help finding this

**Comment by AndroDevcd** [comment]
Yes this answers the concern!
